---
- name: test add host
  hosts: localhost
  vars:
  - ipaddr: 192.168.1.100
  tasks:
  - name: add host to inventory
    add_host:
      name: "{{ ipaddr }}"
      groups: ipaddr

- name: second run
  hosts: ipaddr
  gather_facts: no
  tasks:
  - name: second play
    debug:
      msg: "OK test"
